config/routes.rb
Tawseela::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  scope "(:locale)", :locale => /#{SUPPORTED_LOCALES.join("|")}/ do
    resources :pages, :only => [:show]
    resources :flags, :rates, :notifications
    resources :gasoline_types, :cars_makes, :notifications, :users_requests, :cities, :only => [:index]
    resources :messages, :only => [:index, :show]
    resources :feedbacks, :groups_users, :only => [:new, :create]
    resources :payments do
      member do
        get :confirm
      end
      collection do
        post :cashu_approved
        post :cashu_sorry
      end
    end
    resources :events
    resources :users do 
      resources :transports do
        collection do
          get :transports_requests
        end
      end
      resources :messages do 
        collection do
          get :sent
        end
      end
      resources :notifications, :users_requests, :only => [:index]
      resources :blocks do
        member do
          get :delete
        end
      end
      member do
        get :merge_accounts
        get :update_default_account
        get :dashboard
        put :invite_friends
      end
      collection do
        get :get_token
      end
    end
    resources :searches do
      member do
        get :delete
      end
      collection do
        get :my_searches
        post :results
        get :get_token
      end 
    end
    resources :transports do
      collection do 
        get :upcoming
        get :get_token
      end
      member do
        get :share
      end
      resources :flags, :rates do
        member do
          get :delete
          get :share
        end
      end
      resources :transports_requests do
        resources :flags, :rates do
          member do
            get :delete
          end
        end
        member do
          get :transports_response
          get :reject_request
          put :accept_request
          get :cancel_request
          get :delete
        end
      end
      member do
        get :delete
        put :repeat
      end
    end
    
    match '/login_header' => 'sessions#login_header'
    match '/auth/failure' => 'sessions#failure'
    match '/auth/:provider/callback' => 'sessions#create'
    match '/login/(:provider)' => 'sessions#login', :as => :login
    match '/mobile_login/:provider' => 'sessions#mobile_login', :as => :mobile_login
    match '/logout' => 'sessions#destroy', :as => :logout
    match '/get_current_user' => 'users#get_current_user', :as => :get_current_user
    match '/check_current_user' => 'users#check_current_user', :as => :check_current_user        
    
    root :to => 'pages#show', :id => :home
  
  end

end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  load_resource :find_by => :find_encoded # will use find_by_permalink!(params[:id])
  before_filter :prepare_list, :only => [:new, :results]
  authorize_resource :except => [:show, :upcoming]
  
  def upcoming
    @par = {:user_id => params[:user_id], 
            :lat => params[:lat], 
            :lng => params[:lng],
            :event_time => params[:event_time],
            :limit => !params[:limit].blank? && (params[:limit].to_i > 0 && params[:limit].to_i < 11 ) ? params[:limit].to_i : 5,
            :width => !params[:width].blank? && (params[:width].to_i > 220 ) ? params[:width].to_i : 220 }
    
    
    account = Account.find_by_uid(@par[:user_id].to_s) unless @par[:user_id].blank?
    
    #Transport.uncached do
      if account
        @transports = Transport.next_dates.has_seats.order("start_time asc").where("user_id <> #{account.user_id}").where(:user_id => account.user.friends_ids)
      else
        @transports = Transport.next_dates.has_seats.order("start_time asc")
      end
    #end 
    
    if !@par[:event_time].blank?
      event_time = Time.parse(@par[:event_time])
      @transports = @transports.where("start_time >= '#{event_time - 1.day}'") unless event_time.blank?
      @transports = @transports.where("start_time <= '#{event_time + 1.day}'") unless event_time.blank?
    end
    
    if !@par[:lat].blank? && !@par[:lng].blank?
      points = []
      factory = ::RGeo::Geographic.simple_mercator_factory()
      #points should be more than 1 point 
      points << factory.point(@par[:lng], @par[:lat])
      points << factory.point(@par[:lng], @par[:lat])
      
      transports_ids = TransportsRoute.next_dates.where("ST_Distance(path, ST_GeomFromText('#{factory.line_string(points).as_text}', 4326) ) < 0.0013").select(:transport_id)
      @transports = @transports.where(:id => transports_ids.collect(&:transport_id))
    end
    
    @transports = @transports.limit(@par[:limit])
    
    respond_to do |format|
      format.html {render :layout => false}
      format.js {render :status => :ok}
    end
  end
  
  def index
    #Transport.uncached do
    @transports = current_user.transports.running.order("start_time asc")
    @prev_transports = current_user.transports.previous.order("start_time desc").page(params[:page]).per(Transport.per_page)
    #end
    
    respond_to do |format|
      format.html
      # format.json { render json: @transports }
    end
  end
  
  def show
    @title = @transport.title
    @description = "#{t('tawseela')} - #{l(@transport.start_time, :format => :short)} - #{t('navigation.from')}: #{@transport.start_place}, #{t('navigation.to')}: #{@transport.end_place}"
    
    @transport = Transport.find_encoded(params[:id])
    authorize! :show, @transport
    
    
    @transports_requests = []
    if current_user && current_user.id == @transport.user_id 
      @transports_requests = @transport.transports_requests.order("status asc")
    elsif current_user && !@transport.transports_requests.where(:user_id => current_user.id).accepted.blank?
      @transports_requests = @transport.transports_requests.accepted
    elsif current_user
      @transports_requests = @transport.transports_requests.where(:user_id => current_user.id)
    end
    
    if current_user
      @latest_transports = Transport.next_dates.has_seats.where("user_id <> #{current_user.id}").where("id <> #{@transport.id}").where(:user_id => current_user.friends_ids).limit(5)
    end
    
    flash[:warning] = t("messages.cant_save", :login_link => "<a style='color:#C9581F;font-weight: bold;' href='/login'><strong>#{t('navigation.with_login')}</strong></a>").html_safe unless current_account
    
    respond_to do |format|
      format.html
      format.json { render json: @transport.transport_data(@transports_requests, current_user) }
    end
  end
  
  def new
    if !current_account
      flash[:warning] = t("messages.cant_save", :login_link => "<a style='color:#C9581F' href='/login'><strong>#{t('navigation.with_login')}</strong></a>").html_safe
    elsif current_account.user.has_car != true
      flash[:error] = t("transports.cant_add_transport")
      redirect_to root_path
      return true
    end
    
    
    if params[:saved_transport].blank?
      @transport = Transport.new()
      @saved_transports = current_user ? current_user.transports.saved_only : []
    else
      transport = Transport.find(Encoder.decode(params[:saved_transport]))
      transport_attributes = transport.attributes
      transport_attributes.merge("id" => nil, "start_time" => nil, "templ_saved" => false, "user_id" => nil, "created_at" => nil, "updated_at" => nil, "flags_count" => nil, "rates_count" => nil)
      @transport = Transport.new(transport_attributes)
      @transport.templ_saved = false 
      @transport.start_time = nil
      @transport.cost = 0 if @transport.cost_type == CostType.free
      @transport.saved_transport = params[:saved_transport]
      @transport.paths = transport.points_list_to_hash
    end
  end
  
  def edit
    @transport = Transport.find_encoded(params[:id])
    
    @transport.start_time = "#{l(@transport.start_time, :format => :short)} UTC+2" if !@transport.start_time.blank?
    @transport.return_back_start_time = "#{l(@transport.return_back_start_time, :format => :long)} UTC+2" if !@transport.return_back_start_time.blank? 
  end
  
  def create
    @transport = Transport.new(params[:transport])
    @transport.user = current_user
    @transport.cost = 0 if @transport.cost_type == CostType.free
    # if @transport.cost_type == CostType.free && params[:transport_total_cost].to_f > 0 
    #   cost = (params[:transport_total_cost].to_f * 10 ) / 100 
    #   @transport.cost = cost > 1 ? cost : 1
    # end
    
    if !params[:transport].blank? && !params[:transport][:start_time].blank? && !params[:transport][:start_time].include?("UTC")
      @transport.start_time = "#{params[:transport][:start_time]} UTC+2" 
    elsif !params[:transport_start_time_date_only].blank? && !params[:transport_start_time_time_only].blank?
      @transport.start_time = "#{params[:transport_start_time_date_only]} #{params[:transport_start_time_time_only]} UTC+2"
    end

    if !params[:transport].blank? && !params[:transport][:return_back_start_time].blank? && !params[:transport][:return_back_start_time].include?("UTC")
      @transport.return_back_start_time = "#{params[:transport][:return_back_start_time]} UTC+2" 
    elsif !params[:transport_return_back_start_time_date_only].blank? && !params[:transport_return_back_start_time_time_only].blank?
      @transport.return_back_start_time = "#{params[:transport_return_back_start_time_date_only]} #{params[:transport_return_back_start_time_time_only]} UTC+2"
    end    
    

    @transport = update_geo_route(@transport)
    
    share_msg = ""
    repeat_days = @transport.repeat_days
    
    respond_to do |format|
      begin
        Transport.transaction do
          if @transport.save
            @transport = Transport.find(@transport)
            @transport.repeat_days = repeat_days
            @transport.repeat_days.each do |repeat_day|
              transport_attributes = @transport.attributes
              transport_attributes.merge("id" => nil, "templ_saved" => false, "user_id" => current_user.id, "created_at" => nil, "updated_at" => nil, "flags_count" => nil, "rates_count" => nil, "repeat_days" => nil)
              
              target_time = @transport.start_time.date_of_next(Day.wday_of(repeat_day.to_sym))
              
              new_transport = Transport.new(transport_attributes)
              new_transport.templ_saved = false 
              new_transport.start_time = Time.mktime(target_time.year, target_time.month, target_time.day, @transport.start_time.hour, @transport.start_time.min)
              new_transport.return_back_start_time = Time.mktime(target_time.year, target_time.month, target_time.day, @transport.return_back_start_time.hour, @transport.return_back_start_time.min) unless @transport.return_back_start_time.blank?
              new_transport.paths = @transport.points_list_to_hash
              new_transport = update_geo_route(new_transport)
              new_transport.save
            end if @transport.repeat_days
            
            Notification.create(:user => current_user , :notifiable => @transport, :notification => "notifications.added_transport")
            
            if params[:transport][:share_transport].to_s == "1"
              Resque.enqueue(ProviderShare, @transport.user_id, :transport_share, @transport.user.accounts.collect(&:provider), @transport.id)
              Resque.enqueue(EmailsShare, :new_transport, @transport.id)
              share_msg = t("messages.will_share")
            end
            
            
            
            format.html { redirect_to @transport, notice: t("messages.transport_created") + share_msg }
            format.json { render json: {:transport_id => @transport.id}, status: :created, location: @transport }
          else
            @saved_transports = current_user.transports.saved_only
            format.html { render action: "new" }
            format.json { render json: @transport.errors.full_messages, status: :unprocessable_entity }
          end
        end
      rescue => e
        raise e if Rails.env.development?
        @saved_transports = current_user.transports.saved_only
        @transport.repeat_days = repeat_days
        format.html { render action: "new" }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @transport = Transport.find_encoded(params[:id])
    @transport.attributes = params[:transport]
    @transport.cost = 0 if @transport.cost_type == CostType.free
    # if @transport.cost_type == CostType.free && params[:transport_total_cost].to_f > 0 
    #   cost = (params[:transport_total_cost].to_f * 10 ) / 100 

app/views/transports/_index.html.erb
<div class="content_container">
  <% if params[:controller].to_s == "transports" %>
    <% no_transports_msg = t("transports.not_transports") %>
  <% else %>
    <% no_transports_msg = t("transports.not_transports_long") %>
  <% end %>
  
  <%= render :partial => "/transports/transports", :locals => {:transports => transports, :hint => hint, :title => "التوصيلات الحالية", :no_transports_msg => no_transports_msg}%>
  
  <% if prev_transports.size > 0 %>
  <div class="sub_page_content" id="prev_transports">
    <h3 class="title">التوصيلات السابقة</h3>
    <div class="sub_page_container">
      <div class="list_wrapper">
        <div class="list_container">
          <% prev_transports.each do |transport| %>
            <%= render :partial => "/transports/transport", :locals => {:transport => transport, :adv_view => true}%>
          <% end %>
        </div>
      </div>
      <% if prev_transports.num_pages > 1 %>
      <div class="submit clearfix">
        <%= paginate prev_transports, :window => 1, :right => 0, :left => 0 %>
      </div>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

<% content_for :javascripts do %>
  <%= javascript_include_tag "/javascripts/rails.js", "/javascripts/stars.js" %>
  
  <% if params[:page] && params[:page].to_i > 1 %>
  <script>
    location = "#prev_transports"
  </script>
  <% end %>
<% end %>

app/views/transports/_transport.html.erb
<div class="list_item clearfix">
  <div class="main_logo" >
    <% if current_user %>
      <%= link_to image_tag(transport.user.accounts.default_one.first.image), transport.user, :title => transport.user.name %>
    <% else %>
      <%= link_to image_tag("/images/icons/car.png"),  transport %>
    <% end %>
  </div>
  <div class="main_data small">
    <p class="small">
      <% if adv_view == true %>
        <%= link_to transport.title, transport %>
      <% else %>
        <%= transport.title %>
      <% end %>
    </p>
  </div>
  
  <% if adv_view == true %>
  <div class="all_controls_div"> 
    <div class="controls">
      <% if can? :delete, transport %>
        <%= link_to "", delete_transport_path(transport), :title => t("transports.delete_transport"), :class=>"delete hide_txt", :confirm => "هل أنت متأكد من الحذف ؟" %>
      <% end %>
      
      <% if can? :edit, transport %>
        <%= link_to "", edit_transport_path(transport), :title => t("transports.edit_transport"), :class=>"big_edit hide_txt" %>
      <% end %>
      
      <% if can? :repeat, transport %>
        <%= link_to "", repeat_transport_path(transport), :title => t("transports.repeat_transport"), :class=>"repeat hide_txt", :method => :put, :confirm => "سيتم إضافة التوصيلة بنفس البيانات غدا . .  هل أنت متأكد؟" %>
      <% end %>
      
      <% transport_request = transport.transports_requests.where(:user_id => current_user.id).first if current_user %>
      <% if can? :new, TransportsRequest.new(:transport_id => transport.id) %>
        <%= link_to "", new_transport_transports_request_path(transport), :class=>"ask hide_txt", :title => t("transports_requests.new_request") %>
      <% elsif transport_request %>
        <span class="ask_hover" title="<%= t('transports_requests.requested') %>" ></span>
      <% end %>
      
      <% if can? :new, Flag.new(:flaggable_type => transport.class.name, :flaggable_id => transport.id) %>
        <%= link_to "", new_transport_flag_path(transport), :title => t("flags.flag_transport"), :class=>"flag hide_txt fancybox" %>
      <% end %>
      
      <% transport_flag = transport.flags.where(:user_id => current_user.id).first if current_user%>
      <% if transport_flag && can?(:delete, transport_flag) %>
        <%= link_to "", delete_transport_flag_path(transport, transport_flag), :title => t("flags.unflag_transport"), :class=>"unflag hide_txt", :confirm => "هل أنت متأكد من حذف التبليغ؟" %>
      <% end %>
      
      <% if current_user && can?(:new, Rate.new(:rateable => transport, :user => current_user)) %>
        <%= link_to "", "#" , :class=>"rate hide_txt add_stars", :title => t("rates.rate_transport") %>
      <% end %>
    </div>
    
    <% if current_user && can?(:new, Rate.new(:rateable => transport, :user => current_user)) %>
      <% transport_rate = transport.rates.where(:user_id => current_user.id).first if current_user %>
      <% if transport_rate %>
        <% transport_rate_url = transport_rate_path(transport, transport_rate.id) %>
        <% rate_method = :put %>
      <% else %>
        <% transport_rate_url = transport_rates_path(transport) %>
        <% rate_method = :post %>
      <% end %>
      
      <%= render :partial => "/shared/stars", :locals => {:clickalbe => true, :rate_url => transport_rate_url, :rates_count => transport_rate ? transport_rate.rate : 0, :rate_method => rate_method, :html_class => "for_index"}%>
    <% end %>
  </div>
  <% end %>
  
  <% if !transport.start_place.blank? && !transport.end_place.blank? %>
  <div class="main_data wide">
    <div class="col2 transport_from">
      <label title="التوصيلة تبدأ من "><%= transport.start_place %></label>
    </div>
    <div class="col3 transport_to">
      <label title="التوصيلة تنتهي الى"><%= transport.end_place %></label>
    </div>
  </div>
  <% end %>
  
  <div class="main_data wide">
    <% if adv_view == true %>
    <div class="col4 time"><label title="<%= t('transports.start_time') %>" ><%= l(transport.start_time, :format => :short) %></label></div>
    <% end %>
    <div class="col5 gender"><label title="<%= t('transports.gender') %>" ><%= t("gender.gender_#{transport.gender}")%></label></div>
    <div class="col5 payment"><label title="<%= t('transports.cost') %>" ><%= transport.cost %> <%= t("currency")%></label></div>
    <!-- <div class="col4 access"><label title="<%= t('transports.accessories') %>" ><%= transport.accessories %></label></div> -->
  </div>
</div>

app/views/transports/_transports.html.erb
<div class="sub_page_content" style="margin-bottom: 35px;">
  <h3 class="title"><%= title%></h3>
  <div class="sub_page_container">
    <% if transports.size == 0 %>
      <div class="list_item" >
        <p><%= no_transports_msg %></p>
      </div>
    <% else %>
      <p><%= hint %></p>
    <% end %>
    
    <div class="list_wrapper">
      <div class="list_container">
        <% transports.each do |transport| %>
          <%= render :partial => "/transports/transport", :locals => {:transport => transport, :adv_view => true}%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/transports/_transports_requests.html.erb
<div id="requests_container" class="list_wrapper" style="display: <%= show_requests == true ? 'block' : 'none' %> ;">
  <div class="list_container">
    <% transports_requests.each do |transports_request| %>
    <%= render :partial => "/shared/request", :locals => {:transports_request => transports_request, :show_transport_data => show_transport_data} %>
    <% end %>
    <% if transports_requests.size == 0 %>
      <div class="list_item">
        <p>لا يوجد طلبات حتى الأن</p>
      </div>
    <% end %>
  </div>
</div>

app/views/transports/edit.html.erb
<div class="main_page_content">
  <h2 class="page_title"><%= t("transports.edit_transport") %></h2>
  <div class="content_container">
    <%= render :partial => '/transports/form', :locals=>{:transport => @transport, :saved_transports => @saved_transports} %>
  </div>
</div>

<% content_for :sidebar do %>
  <%= render "/shared/sidebar/my_transports" %>
<% end %>

app/views/transports/index.html.erb
<div class="main_page_content">
  <h2 class="page_title"><%= t("transports.transports")%></h2>
  <%= render :partial => "/transports/index", :locals => {:transports => @transports, :prev_transports => @prev_transports, :hint => t("transports.hint_3")}%>
</div>

<% content_for :sidebar do %>
  <%= render "/shared/sidebar/new_transport" %>
  <%= render "/shared/sidebar/like_box" %>
  <%= render "/shared/sidebar/invite_friends" %>
<% end %>

app/views/transports/new.html.erb
<div class="main_page_content">
  <h2 class="page_title"><%= t("transports.new_transport") %></h2>
  <div class="content_container">
    <%= render :partial => '/transports/form', :locals=>{:transport => @transport, :saved_transports => @saved_transports} %>
  </div>
</div>

<% content_for :sidebar do %>
  <%= render :partial => "/shared/sidebar/latest_users", :locals=>{:users => @latest_users} %>
  <%= render "/shared/sidebar/invite_friends" %>
  <%= render "/shared/sidebar/like_box" %>
<% end %>

app/views/transports/transports_requests.html.erb
<div class="main_page_content">
  <h2 class="page_title"><%= t("navigation.transports_requests") %></h2>
  <div class="content_container">
      <div class="sub_page_container">
        <p>طلبات التوصيلات التي قمت بإرسالها . . . </p>
        <div class="list_wrapper">
          <div class="list_container">
            <%= render :partial => "/transports/transports_requests", :locals => {:transports_requests => @transports_requests, :show_requests => true, :show_transport_data => true}%>
          </div>
        </div>
      </div>
  </div>
  
  <% if @transports_requests.num_pages > 1 %>
  <div class="submit clearfix">
    <%= paginate @transports_requests %>
  </div>
  <% end %>
</div>

<% content_for :sidebar do %>
  <%= render "/shared/sidebar/transport_search" %>
  <%= render "/shared/sidebar/like_box" %>
  <%= render "/shared/sidebar/invite_friends" %>
  <%= render "/shared/sidebar/groups_users" %>
<% end %>

app/views/transports/upcoming.html.erb
<style>
@charset "utf-8";
html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video{margin:0; padding:0; border:0; font-size:100%; font:inherit; vertical-align:baseline;}
ol,ul{list-style:none;}
body,td,th{font-family: Arial, Helvetica, sans-serif; font-size:13px; color:#000000; line-height:1.5;}
body{margin:0;}
a, a:link, a:visited, a:hover,a:active{font-family:Arial, Helvetica, sans-serif; font-size:1em; color:#000000; text-decoration:none;}
a:hover{text-decoration:none; color:#fbae40; cursor:pointer;}
h1,h2,h3,h4,h5,h6{font-family: Arial, Helvetica, sans-serif;}
h1{font-size:2.4em; color:#ff6302;}
h2{font-size:2em; color:#000000;}

.side_bar{float:left; width: <%= @par[:width] %>px;}
.side_page_content{padding:1px 0px 10px 0px;}
.side_page_content .side_page_title{width:<%= @par[:width] - 45 %>px; background:#C9581F; -moz-border-radius:10px;-webkit-border-radius:10px; border-radius:10px; padding:0 10px; border:2px solid #E2BF8C; color:#ffffff; float:right; margin: 0 11px; text-align: center;}
.content_container{padding:10px; background:#ffffff; -moz-border-radius:10px;-webkit-border-radius:10px; border-radius:10px; padding-top:30px; margin-top:25px; border:3px solid #E2BF8C;}

ul{list-style: none;margin: 0px;padding: 0px;}
.side_list{}
.side_list li{height: 50px; border-bottom: 1px solid #E2BF8C; margin-bottom: 15px;}
.side_list img{float:right;}
.side_list div.data{float: right; margin-right: 10px; text-align: right;}
</style>


<div class="side_bar">
  <div class="side_page_content">
    <h2 class="side_page_title" title="موقع توصيلة - خد حد معاك فى سكتك"><a href="http://www.temporary.com/" target="_blank">موقع توصيلة</a></h2>
    <div class="content_container">
      <ul class="side_list">
        <li style="text-align: right;  border-bottom: none;" >
          أبحث عن مواصلة فى نطاق أصدقائك الذين يمتلكون سيارات وأبحث ايضا عن أحد أصدقائك ليكون رفيقك فى الطريق للوصول الى مكان الحدث
        </li>
        
        <li style="text-align: right; height: 38px; padding-right: 10px;" >
          <h2>آخر التوصيلات</h2>
        </li>
        
        <% if @transports.size == 0 %>
        <div style="text-align: center;">
        <h3 style="font-size: 16px; ">لا يوجد توصيلات متاحة لنفس المكان وفي نفس الوقت</h3>
        <a style="font-weight: bolder; color: #C9581F;" href="http://temporary.com/transports/new" target="_blank">أضف توصيلة وخد حد معاك فى سكتك</a>
        </div>
        <% end %>
        
        <% @transports.each do |transport| %>
          <li>
            <a href="<%= transport_url(transport) %>" target="_blank"><img alt="Picture?type=square" src="http://www.temporary.com/images/main/ver_small_car.png" style="height: 48px;" title="Nesma Mohamed"></a>
            <div class="data">
              <%= link_to transport.title, transport_url(transport), :target => "_blank", :style => "color: #C9581F; font-weight: bolder; font-size: 14px;" %>
              <div><%= l(transport.start_time, :format => :short) %></div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>