config/routes.rb
Tawseela::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  scope "(:locale)", :locale => /#{SUPPORTED_LOCALES.join("|")}/ do
    resources :pages, :only => [:show]
    resources :flags, :rates, :notifications
    resources :gasoline_types, :cars_makes, :notifications, :users_requests, :cities, :only => [:index]
    resources :messages, :only => [:index, :show]
    resources :feedbacks, :groups_users, :only => [:new, :create]
    resources :payments do
      member do
        get :confirm
      end
      collection do
        post :cashu_approved
        post :cashu_sorry
      end
    end
    resources :events
    resources :users do 
      resources :transports do
        collection do
          get :transports_requests
        end
      end
      resources :messages do 
        collection do
          get :sent
        end
      end
      resources :notifications, :users_requests, :only => [:index]
      resources :blocks do
        member do
          get :delete
        end
      end
      member do
        get :merge_accounts
        get :update_default_account
        get :dashboard
        put :invite_friends
      end
      collection do
        get :get_token
      end
    end
    resources :searches do
      member do
        get :delete
      end
      collection do
        get :my_searches
        post :results
        get :get_token
      end 
    end
    resources :transports do
      collection do 
        get :upcoming
        get :get_token
      end
      member do
        get :share
      end
      resources :flags, :rates do
        member do
          get :delete
          get :share
        end
      end
      resources :transports_requests do
        resources :flags, :rates do
          member do
            get :delete
          end
        end
        member do
          get :transports_response
          get :reject_request
          put :accept_request
          get :cancel_request
          get :delete
        end
      end
      member do
        get :delete
        put :repeat
      end
    end
    
    match '/login_header' => 'sessions#login_header'
    match '/auth/failure' => 'sessions#failure'
    match '/auth/:provider/callback' => 'sessions#create'
    match '/login/(:provider)' => 'sessions#login', :as => :login
    match '/mobile_login/:provider' => 'sessions#mobile_login', :as => :mobile_login
    match '/logout' => 'sessions#destroy', :as => :logout
    match '/get_current_user' => 'users#get_current_user', :as => :get_current_user
    match '/check_current_user' => 'users#check_current_user', :as => :check_current_user        
    
    root :to => 'pages#show', :id => :home
  
  end

end

app/views/shared/sidebar/_block_list.html.erb
<div class="side_page_content">
  <h2 class="side_page_title"><%= link_to t("sidebar.block_list"), user_blocks_path(current_user) %></h2>
  <div class="content_container">
    <p><%= t("sidebar.block_list_hint")%> </p>
    <span><%= link_to image_tag("/images/graphic/blocked.png"), user_blocks_path(current_user) %></span>
  </div>
</div>

app/views/shared/sidebar/_faq.html.erb
<div class="side_page_content">
  <h2 class="side_page_title"><%= link_to t("sidebar.faq"), page_path(:FAQ) %></h2>
  <div class="content_container">
    <p><%= t("sidebar.faq_hint")%> </p>
    <span><%= link_to image_tag("/images/graphic/faq.png"), page_path(:FAQ) %></span>
  </div>
</div>

app/views/shared/sidebar/_feedback.html.erb
<div class="side_page_content">
  <h2 class="side_page_title"><%= link_to t("sidebar.feedback"), new_feedback_path %></h2>
  <div class="content_container">
    <p><%= t("sidebar.feedback_hint")%> </p>
    <span><%= link_to image_tag("/images/graphic/feedback.png"), new_feedback_path %></span>
  </div>
</div>

app/views/shared/sidebar/_friends.html.erb
<% if current_user %>
<div class="side_page_content">
  <h2 class="side_page_title"><%= link_to t("sidebar.friends"), users_path %></h2>
  <div class="content_container">
    <p><%= t("sidebar.friends_hint")%> </p>
    <span><%= link_to image_tag("/images/graphic/friends.png"), users_path %></span>
  </div>
</div>
<% end %>

app/views/shared/sidebar/_groups_users.html.erb
<% if can? :new, GroupsUser.new %>
<div class="side_page_content">
  <h2 class="side_page_title"><%= link_to t("sidebar.groups_users"), new_groups_user_path %></h2>
  <div class="content_container">
    <p>قم بإضافة اصدقاء جدد للشبكات الخاصة بك.</p>
    <span><%= link_to image_tag("/images/graphic/add_friends.png"), new_groups_user_path %></span>
  </div>
</div>
<% end %>

app/views/shared/sidebar/_how_it_works.html.erb
<div class="side_page_content">
  <h2 class="side_page_title"><%= link_to t("sidebar.how_it_works"), page_path(:how_it_works) %></h2>
  <div class="content_container">
    <p><%= t("sidebar.how_it_works_hint")%> </p>
    <span><%= link_to image_tag("/images/graphic/how_it_works.png"), page_path(:how_it_works) %></span>
  </div>
</div>

app/views/shared/sidebar/_latest_transports.html.erb
<% if transports.size > 0 %>
<div class="side_page_content">
  <h2 class="side_page_title"><%= t("sidebar.lastest_transports") %></h2>
  <div class="content_container">
    <ul class="side_list">
      <% transports.each do |transport|%>
      <li>
        <%= link_to image_tag(transport.user.accounts.default_one.first.my_image(:square), :title => transport.user.name, :style => "height: 48px;"), transport.user %>
        <div class="data">
          <a href="<%= transport_path(transport)%>" >
            <div><%= transport.title %></div>
            <div><%= l(transport.start_time, :format => :short) %></div>
          </a>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/shared/sidebar/_latest_users.html.erb
<% if current_user && users && users.size > 0 %>
<div class="side_page_content">
  <h2 class="side_page_title"><%= link_to t("sidebar.lastest_users"), users_path %></h2>
  <div class="content_container">
    <ul class="side_users_list">
      <% users.each do |user|%>
        <li><%= link_to image_tag(user.accounts.default_one.first.my_image(:square), :title => user.name, :style => "height: 48px;"), user, :target => "_blank" %></li>
      <% end %>
    </ul>
    <div class="clearfix"></div>
  </div>
</div>
<% end %>

app/views/shared/sidebar/_like_box.html.erb
<div class="side_page_content">
  <h2 class="side_page_title"><%= link_to "على الفيسبوك", page_path(:invite_friends)%></h2>
  <div class="content_container white_span">
    <%= render :partial => "/shared/fb/fb_like", :locals => {:fb_width => "265"} %>
  </div>
</div>

app/views/shared/sidebar/_merge_accounts.html.erb
<% if current_user %>
<div class="side_page_content">
  <h2 class="side_page_title"><%= link_to t("sidebar.merge_accounts"), merge_accounts_user_path(current_user) %></h2>
  <div class="content_container">
    <p><%= t("sidebar.merge_accounts_hint")%> </p>
    <span><%= link_to image_tag("/images/graphic/merge.png"), merge_accounts_user_path(current_user) %></span>
  </div>
</div>
<% end %>

app/views/shared/sidebar/_my_transports.html.erb
<div class="side_page_content">
  <h2 class="side_page_title"><%= link_to t("sidebar.my_transports"), transports_path %></h2>
  <div class="content_container">
    <p><%= t("sidebar.my_transports_hint")%> </p>
    <span><%= link_to image_tag("/images/graphic/my_transports.png"), transports_path %></span>
  </div>
</div>

app/views/shared/sidebar/_new_transport.html.erb
<% if !current_user || can?(:new, Transport.new) %>
<div class="side_page_content">
  <h2 class="side_page_title"><%= link_to t("sidebar.new_transport"), new_transport_path %></h2>
  <div class="content_container">
    <p><%= t("sidebar.new_transport_hint")%> </p>
    <span><%= link_to image_tag("/images/graphic/new_transport.png"), new_transport_path %></span>
  </div>
</div>
<% end %>

app/views/shared/sidebar/_share.html.erb
<div class="side_page_content">
  <h2 class="side_page_title"><%= t("sidebar.share") %></h2>
  <div class="content_container">
    <p><%= t("sidebar.share_hint")%> </p>
    <span><%= link_to image_tag("/images/graphic/share.png"), share_link, :confirm => "هل أنت متاكد من نشر التوصيلة ؟" %></span>
  </div>
</div>

app/views/shared/sidebar/_transport_search.html.erb
<% if !current_user || !current_user.has_car %>
<div class="side_page_content">
  <h2 class="side_page_title"><%= link_to t("sidebar.transport_search"), new_search_path %></h2>
  <div class="content_container">
    <p><%= t("sidebar.transport_search_hint")%> </p>
    <span><%= link_to image_tag("/images/graphic/transport_search.png"), new_search_path %></span>
  </div>
</div>
<% end %>