config/routes.rb
Tawseela::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  scope "(:locale)", :locale => /#{SUPPORTED_LOCALES.join("|")}/ do
    resources :pages, :only => [:show]
    resources :flags, :rates, :notifications
    resources :gasoline_types, :cars_makes, :notifications, :users_requests, :cities, :only => [:index]
    resources :messages, :only => [:index, :show]
    resources :feedbacks, :groups_users, :only => [:new, :create]
    resources :payments do
      member do
        get :confirm
      end
      collection do
        post :cashu_approved
        post :cashu_sorry
      end
    end
    resources :events
    resources :users do 
      resources :transports do
        collection do
          get :transports_requests
        end
      end
      resources :messages do 
        collection do
          get :sent
        end
      end
      resources :notifications, :users_requests, :only => [:index]
      resources :blocks do
        member do
          get :delete
        end
      end
      member do
        get :merge_accounts
        get :update_default_account
        get :dashboard
        put :invite_friends
      end
      collection do
        get :get_token
      end
    end
    resources :searches do
      member do
        get :delete
      end
      collection do
        get :my_searches
        post :results
        get :get_token
      end 
    end
    resources :transports do
      collection do 
        get :upcoming
        get :get_token
      end
      member do
        get :share
      end
      resources :flags, :rates do
        member do
          get :delete
          get :share
        end
      end
      resources :transports_requests do
        resources :flags, :rates do
          member do
            get :delete
          end
        end
        member do
          get :transports_response
          get :reject_request
          put :accept_request
          get :cancel_request
          get :delete
        end
      end
      member do
        get :delete
        put :repeat
      end
    end
    
    match '/login_header' => 'sessions#login_header'
    match '/auth/failure' => 'sessions#failure'
    match '/auth/:provider/callback' => 'sessions#create'
    match '/login/(:provider)' => 'sessions#login', :as => :login
    match '/mobile_login/:provider' => 'sessions#mobile_login', :as => :mobile_login
    match '/logout' => 'sessions#destroy', :as => :logout
    match '/get_current_user' => 'users#get_current_user', :as => :get_current_user
    match '/check_current_user' => 'users#check_current_user', :as => :check_current_user        
    
    root :to => 'pages#show', :id => :home
  
  end

end

app/views/shared/_flag.html.erb
<div class="list_item short_long high">
  <div class="main_logo">
    <img src="/images/icons/user_big.png">
  </div>
  <div class="main_data">
    <div class="col2 flag_weight"><label class="bold"><%= t("trust_level.level_#{flag.level}") %> </label> <%= flag.flag %></div>
  </div>
</div>

app/views/shared/_follow_twseela.html.erb
<div class="sub_page_content" style="margin-bottom: 35px;">
  <h3 class="title">تابعنا</h3>
  <div class="sub_page_container" style="text-align: center;">
    <div class="col2">
      <%= link_to(image_tag("/images/graphic/facebook_home.png"), FACEBOOK_PAGE, :target => "_blank")%>
    </div>
    <div class="col2">
      <%= link_to(image_tag("/images/graphic/twitter_home.png"), TWITTER_PAGE, :target => "_blank" )%>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/shared/_form_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= t("errors.errors_title") %></h2>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    <div class="clear"></div>
  </div>
<% end %>

app/views/shared/_latest_slider.html.erb
<style type="text/css" media="all">
#news-container {
  margin: auto;
  margin-top: 30px;
}
</style>
    
<div class="sub_page_content" style="margin-bottom: 35px;">
  <h3 class="title">توصيلات سابقة</h3>
  <div class="sub_page_container">
    <div class="list_wrapper" id="news-container" style="overflow: hidden; position: relative; height: 430px;">
      <ul class="list_container" style="position: absolute; margin: 0px; padding: 0px; top: 0px;">
        <% transports.each do |transport| %>
        <li style="margin: 0px; padding: 0px; height: 130px; display: list-item;">
          <div>
            <%= render :partial => "/transports/transport", :locals => {:transport => transport, :adv_view => false}%>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<%= content_for :javascripts do %>
  <%= javascript_include_tag "/javascripts/jquery.vticker-min.js" %>
  
  <script type="text/javascript">
  $( function() {
    $('#news-container').vTicker({
      speed: 500,
      pause: 4000,
      animation: 'fade',
      mousePause: false,
      showItems: 3,
      height: 430
    });
  });
  </script>
<% end %>

app/views/shared/_map_btn.html.erb
<li class="btn_itm">
  <div class="car_btn"><a href="#" id="car_btn_click" title="كتابة وتحديد مسار التوصيلة" ></a></div>
  <div id="v_content_container" class="values_container">
    <div class="values_window">
      <div class="v_content">
        <div class="saved_value">
          <label>بداية التوصيلة</label>
          <span><input id="transport_start_point" type="text" class="input_txt larage" placeholder="مثال : الاسكندرية ، العصافرة"/></span>
          <span><input type="button" class="larage" value="بحث" onclick="codeAddress('transport_start_point')"/></span>
        </div>
        <div class="saved_value">
          <label>نهاية التوصيلة</label>
          <span><input id="transport_end_point" type="text" class="input_txt larage" placeholder="مثال : الاسكندرية ، رشدي"/></span>
          <span><input type="button" class="larage" value="بحث" onclick="codeAddress('transport_end_point')"/></span>
        </div>
        <div class="saved_value">
          <label>المسار</label>
          <span><input id="transport_path_points" type="text" class="input_txt large" placeholder="مثال : سيدي بشر ، ستانلي ، جليم"/></span>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/shared/_map_hints.html.erb
<li class="btn_itm">
  <div class="car_btn"><a href="#" id="map_hint_click" class="map_hint" title="كيفية تحديد مسار التوصيلة على الخريطة"></a></div>
  <div id="map_hint_container" class="values_container">
    <div class="values_window">
      <div class="v_content">
        <p>لتحديد مسار التوصيلة على الخريطة فقط قم بالضغط على مكان بداية التوصيلة بالزر الايسر للماوس بعد ذلك اضغط على كل النقاط التي ستمر بها خلال التوصيلة.</p>
        <p>يمكنك تغيير مكان اي نقطة بسحب العلامة عند كل نقطة.</p>
        <p>ولحذف احدى النقاط انقر عليها بالزر الايمن للماوس.</p>
        <div class="saved_value" style="height: 55px;">
          <div class="col5">
            <label>بداية التوصيلة</label>
            <img src="/images/icons/marker_green.png" style="margin-right: 20px;" />
          </div>
          <div class="col5">
            <label>مسار التوصيلة</label>
            <img src="/images/icons/marker.png" style="margin-right: 20px;" />
          </div>
          <div class="col5">
            <label>نهاية التوصيلة</label>
            <img src="/images/icons/marker_red.png" style="margin-right: 20px;" />
          </div>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/shared/_map_hints_2.html.erb
<li class="btn_itm">
  <div class="car_btn"><a href="#" id="map_hint_click" class="map_hint" title="كيفية تحديد مكان المقابلة على الخريطة"></a></div>
  <div id="map_hint_container" class="values_container">
    <div class="values_window">
      <div class="v_content">
        <p>لتحديد مكان المقابلة على الخريطة فقط قم بالضغط على المكان في الخريطة بالزر الأيسر للماوس.</p>
        <p>يمكنك تغيير مكان اي نقطة بالضغط على اي مكان أخر على الخريطة.</p>
        <p>ولحذف النقطة انقر عليها بالزر الايمن للماوس.</p>
        <div class="saved_value" style="height: 55px;">
          <div class="col5">
            <label>مكان المقابلة</label>
            <img src="/images/icons/marker_user.png" style="margin-right: 20px;" />
          </div>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/shared/_map_hints_3.html.erb
<li class="btn_itm">
  <div class="car_btn"><a href="#" id="map_hint_click" class="map_hint" title="تعرف على معاني الرموز على الخريطة"></a></div>
  <div id="map_hint_container" class="values_container">
    <div class="values_window">
      <div class="v_content">
        <p>تعرف على معاني الرموز على الخريطة</p>
        <div class="saved_value" style="height: 55px;">
          <div class="col6">
            <label>بداية التوصيلة</label>
            <img src="/images/icons/marker_green.png" style="margin-right: 20px;" />
          </div>
          <div class="col5">
            <label>مسار التوصيلة</label>
            <img src="/images/icons/marker.png" style="margin-right: 20px;" />
          </div>
          <div class="col5">
            <label>نهاية التوصيلة</label>
            <img src="/images/icons/marker_red.png" style="margin-right: 20px;" />
          </div>
          <div class="col5">
            <label>مكان المقابلة</label>
            <img src="/images/icons/marker_user.png" style="margin-right: 20px;" />
          </div>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/shared/_request.html.erb
<div class="list_item auto high">
  <div class="main_logo">
    <%= link_to image_tag(transports_request.user.accounts.default_one.first.image), transports_request.user, :title => transports_request.user.name %>
  </div>
  <% if current_user && transports_request.transport.user_id == current_user.id %>
    <%= render :partial => "/shared/transporter_controls", :locals => {:transports_request => transports_request} %>
  <% else %>
    <%= render :partial => "/shared/requester_controls", :locals => {:transports_request => transports_request} %>
  <% end %>
  <div class="main_data auto">
    <div class="col5 seats"><label title="<%= t('transports.requested_seats') %>" ><%= transports_request.for_persons %></label></div>
    <div class="col5 payment"><label title="<%= t('transports.cost') %>" ><%= number_to_currency(transports_request.requester_cost, :precision => 2, :unit => t("currency"), :format => " %u %n ") %></label></div>
  </div>
  
  <% if show_transport_data == true %>
  <div class="main_data wide auto">
    <div class="col3 small_car"><label title="<%= t('transports.title') %>" ><a href="<%= transport_path(transports_request.transport) %>"><%= transports_request.transport.title %></a></label></div>
    <div class="col3 time"><label title="<%= t('transports.start_time') %>" ><%= l(transports_request.transport.start_time, :format => :short) %></label></div>
  </div>
  <% end %>
  
  
  <div class="main_data wide auto">
    <div class="col3 place"><label title="<%= t('transports.place') %>" ><%= transports_request.requester_meet_place %></label></div>
    <% unless transports_request.transporter_meet_time.blank? %>
      <div class="col3 time"><label title="<%= t('transports_requests.transporter_meet_time') %>" ><%= l(transports_request.transporter_meet_time, :format => :short) %></label></div>
    <% end %>
  </div>
  <% if transports_request.requester_return_back %>
    <div class="main_data wide auto">
      <div class="col4 return"><label title="<%= t('transports.return_back') %>" >عودة</label></div>
      <div class="col4 place_return"><label title="<%= t('transports.return_back_meet_place') %>" ><%= transports_request.requester_return_back_meet_place %></label></div>
      <% unless transports_request.transporter_return_back_meet_time.blank? %>
        <div class="col4 time"><label title="<%= t('transports.transporter_return_back_meet_time') %>" ><%= l(transports_request.transporter_return_back_meet_time, :format => :short) %></label></div>
      <% end %>
    </div>
  <% end %>
  <% unless transports_request.requester_message.blank? %>
    <div class="main_data wide auto">
      <div class="message" title="<%= t('transports_requests.requester_message') %>"><%= transports_request.requester_message %></div>
    </div>
  <% end %>
  <% unless transports_request.transporter_message.blank? %>
    <div class="main_data wide auto">
      <div class="message" title="<%= t('transports_requests.transporter_message') %>"><%= transports_request.transporter_message %></div>
    </div>
  <% end %>
  
  <div class="clear"></div>
</div>

app/views/shared/_requester_controls.html.erb
<div class="controls controls_hover">
  <% if transports_request.status == Status.accepted %>
    <span class="accept_hover hide_txt" title="<%= t('transports_requests.accepted') %>" ></span>
  <% elsif transports_request.status == Status.rejected %>
    <span class="reject_hover hide_txt" title="<%= t('transports_requests.rejected') %>" ></span>
  <% elsif transports_request.status == Status.requested %>
    <span class="waiting hide_txt" title="<%= t('transports_requests.waiting') %>" ></span>
  <% elsif transports_request.status == Status.canceled %>
    <span class="cancel hide_txt" title="<%= t('transports_requests.cancelled') %>" ></span>
  <% elsif transports_request.status == Status.completed %>
    <span class="completed hide_txt" title="<%= t('transports_requests.completed') %>" ></span>
  <% end %>
</div>

<% if can? :edit, transports_request%>
<div class="controls">
  <% if transports_request.status == Status.requested || transports_request.status == Status.accepted %>
    <%= link_to "", cancel_request_transport_transports_request_path(transports_request.transport, transports_request), :class => "cancel hide_txt", :confirm => "هل أنت متأكد من إلغاء الطلب؟", :title => t('transports_requests.cancel') %>
  <% end %>
</div>
<% end %>

app/views/shared/_stars.html.erb
<% if clickalbe == true %>
  <div class="stars_container stars clickalbe <%= html_class %>" style="display: none;">
    <% 5.times.each do |index| %>
      <%= link_to "", rate_url + "?rate=#{index+1}", :class => "#{rates_count >= index+1 ? 'rated with_vote' : 'rate with_no_vote'} hide_txt clickalbe", :id => "star_#{index + 1}", :method => rate_method %>
    <% end %>
  </div>
<% else %>
  <% msg = rates_count > 0 ? "متوسط التقييمات التي تمت" : "لم يتم التقييم حتى الان" %>
  <div class="stars_container stars top" title="<%= msg%>">
    <% 5.times.each do |index| %>
      <span class="<%= rates_count >= index+1 ? 'rated with_vote' : 'rate with_no_vote' %> hide_txt"></span>
    <% end %>
  </div>
<% end %>

app/views/shared/_transporter_controls.html.erb
<div class="controls controls_hover">
  <% if transports_request.status == Status.accepted %>
    <span class="accept_hover hide_txt" title="<%= t('transports_requests.accepted') %>" ></span>
  <% elsif transports_request.status == Status.rejected %>
    <span class="reject_hover hide_txt" title="<%= t('transports_requests.rejected') %>" ></span>
  <% elsif transports_request.status == Status.canceled %>
    <span class="cancel hide_txt" title="<%= t('transports_requests.cancelled') %>" ></span>
  <% elsif transports_request.status == Status.completed %>
    <span class="completed hide_txt" title="<%= t('transports_requests.completed') %>" ></span>
  <% end %>
</div>
<div class="all_controls_div">
  <div class="controls">
    <% transports_request_flag = transports_request.flags.where(:user_id => current_user.id).first %>
    <% if transports_request_flag %>
      <%= link_to '', delete_transport_transports_request_flag_path(transports_request.transport, transports_request, transports_request_flag.id), :class => "unflag hide_txt", :confirm => "هل أنت متأكد من حذف التبليغ؟", :title => t("transports_requests.unflag_request") %>
    <% else %>
      <% if can? :new, Flag.new(:flaggable => transports_request) %>
        <%= link_to '', new_transport_transports_request_flag_path(transports_request.transport, transports_request), :class => "flag hide_txt", :title => t("transports_requests.flag_request") %>
      <% end %>
    <% end %>
    <% if transports_request.status == Status.requested %>
      <% if can? :reject_request, transports_request %>
      <%= link_to "", reject_request_transport_transports_request_path(transports_request.transport, transports_request), :class => "reject hide_txt", :confirm => "هل أنت متأكد من رفض الطلب؟", :title => t("transports_requests.reject") %>
      <% end %>
      
      <% if can? :transports_response, transports_request %>
      <%= link_to "", transports_response_transport_transports_request_path(transports_request.transport, transports_request), :class => "accept hide_txt", :title => t("transports_requests.accept") %>
      <% end %>
    <% elsif transports_request.status == Status.accepted %>
      <% if can? :new, Rate.new(:rateable => transports_request, :user => current_user) %>
        <%= link_to "", "#" , :class=>"rate hide_txt add_stars", :title => t("rates.rate_transports_request") %>
      <% end %>
    <% end %>
  </div>
  <% if can? :new, Rate.new(:rateable => transports_request, :user => current_user) %>
    <% transports_request_rate = transports_request.rates.where(:user_id => current_user.id).first %>
    <% if transports_request_rate %>
      <% transports_request_rate_url = transport_transports_request_rate_path(transports_request.transport, transports_request, transports_request_rate.id) %>
      <% rate_method = :put %>
    <% else %>
      <% transports_request_rate_url = transport_transports_request_rates_path(transports_request.transport, transports_request) %>
      <% rate_method = :post %>
    <% end %>
    
    <%= render :partial => "/shared/stars", :locals => {:clickalbe => true, :rate_url => transports_request_rate_url, :rates_count => transports_request_rate ? transports_request_rate.rate : 0, :rate_method => rate_method, :html_class => "for_index"}%>
  <% end %>
</div>

app/views/shared/_twseela_hint.html.erb
<div class="sub_page_content" style="margin-bottom: 35px;">
  <h3 class="title">خد حد فى سكتك</h3>
  <div class="sub_page_container">
    <p>لما يكون في اشخاص كتير معاهم عربيات وبيروحوا مشواير متكررة يوميا زي الشغل مثلا او بيروحوا بيها مشاوير بعيدة أو سفر أو حضور مؤتمرات او ما شبه ذلك ، واغلب العربيات بيكون فيها شخص واحد فقط، ده بجانب مصاريف البنزين المكلفة.</p>
    <div class="center_text">
      <p>خد حد معاك تعرفه فى سكتك، والي حيجي معاك ممكن يشارك فى تكلفة البنزين</p>
    </div>
    <p>لما نجمع بين الي معاه عربية وبين الي عاوز توصيلة ، والي عاوز توصيلة يساهم بالقليل من مصاريف التوصيلة ، كده الي معاه عربية حيوفر جزء من تكلفة البنزين والي عاوز توصيلة حيوفر كتير من تكلفة المواصلات وحيوفر فى الوقت كمان.</p>
  </div>
</div>

app/views/shared/_woopra.html.erb
<!-- Start of Woopra Code -->
<script type="text/javascript">
function woopraReady(tracker) {
    tracker.setDomain('temporary.com');
    tracker.setIdleTimeout(300000);
    tracker.track();
    return false;
}
(function() {
    var wsc = document.createElement('script');
    wsc.src = document.location.protocol+'//static.woopra.com/js/woopra.js';
    wsc.type = 'text/javascript';
    wsc.async = true;
    var ssc = document.getElementsByTagName('script')[0];
    ssc.parentNode.insertBefore(wsc, ssc);
})();
</script>
<!-- End of Woopra Code -->