config/routes.rb
Tawseela::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  scope "(:locale)", :locale => /#{SUPPORTED_LOCALES.join("|")}/ do
    resources :pages, :only => [:show]
    resources :flags, :rates, :notifications
    resources :gasoline_types, :cars_makes, :notifications, :users_requests, :cities, :only => [:index]
    resources :messages, :only => [:index, :show]
    resources :feedbacks, :groups_users, :only => [:new, :create]
    resources :payments do
      member do
        get :confirm
      end
      collection do
        post :cashu_approved
        post :cashu_sorry
      end
    end
    resources :events
    resources :users do 
      resources :transports do
        collection do
          get :transports_requests
        end
      end
      resources :messages do 
        collection do
          get :sent
        end
      end
      resources :notifications, :users_requests, :only => [:index]
      resources :blocks do
        member do
          get :delete
        end
      end
      member do
        get :merge_accounts
        get :update_default_account
        get :dashboard
        put :invite_friends
      end
      collection do
        get :get_token
      end
    end
    resources :searches do
      member do
        get :delete
      end
      collection do
        get :my_searches
        post :results
        get :get_token
      end 
    end
    resources :transports do
      collection do 
        get :upcoming
        get :get_token
      end
      member do
        get :share
      end
      resources :flags, :rates do
        member do
          get :delete
          get :share
        end
      end
      resources :transports_requests do
        resources :flags, :rates do
          member do
            get :delete
          end
        end
        member do
          get :transports_response
          get :reject_request
          put :accept_request
          get :cancel_request
          get :delete
        end
      end
      member do
        get :delete
        put :repeat
      end
    end
    
    match '/login_header' => 'sessions#login_header'
    match '/auth/failure' => 'sessions#failure'
    match '/auth/:provider/callback' => 'sessions#create'
    match '/login/(:provider)' => 'sessions#login', :as => :login
    match '/mobile_login/:provider' => 'sessions#mobile_login', :as => :mobile_login
    match '/logout' => 'sessions#destroy', :as => :logout
    match '/get_current_user' => 'users#get_current_user', :as => :get_current_user
    match '/check_current_user' => 'users#check_current_user', :as => :check_current_user        
    
    root :to => 'pages#show', :id => :home
  
  end

end

app/models/search.rb
class Search < ActiveRecord::Base
  attr_accessor :save_search
  
  belongs_to :user
  has_many :searches_paths, :dependent=>:destroy
  
  validates :search_name, :presence=>true, :if => Proc.new{|s| s.save_search == true}
  validates :start_time_from, :presence=>true, :unless => Proc.new{|s| s.start_time_to.blank? }
  validates :start_time_to, :presence=>true, :unless => Proc.new{|s| s.start_time_from.blank? }
  validate :presence_one_field
  
  
  def presence_one_field
    errors[:base] << I18n.t("messages.select_any_attribute") if self.save_search.to_i == 1 && self.start_time_from.blank? && self.start_time_to.blank? && self.gender.blank? && !self.return_back && self.searches_paths.blank?
  end
  
  accepts_nested_attributes_for :searches_paths, :reject_if => proc{|attrs| attrs.all? {|k, v| v.blank?}}
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_filter :prepare_list, :only => [:new, :results]
  
  def my_searches
    @searches = current_user ? current_user.searches : []
    authorize! :my_searches, @searches
  end
  
  def results
    params[:search] ||= {}
    @search = Search.new(params[:search].merge(:user_id => current_user.try(:id)))
    authorize! :results, @search
    
    if @search.valid? 
      search_results(@search)
      @search.save if @search.save_search.to_i == 1
    end
    
    respond_to do |format|
      if @search.valid?
        format.html do
          flash[:notice] = t("messages.search_saved") if @search.save_search.to_i == 1
        end
        format.json { render json: Transport.transports_data(@transports)}
      else
        format.html { render action: "new" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @search = Search.find(params[:id])
    authorize! :show, @search
    
    search_results(@search)
    
    respond_to do |format|
      format.html 
      format.json { render json: @transports }
    end
  end
  
  def new
    @search = Search.new
    authorize! :new, @search
    
    if current_user
      flash_warning = nil
      @transports_list = Transport.next_dates.has_seats.order("start_time asc").where("user_id <> #{current_user.id}").where(:user_id => current_user.friends_ids).limit(5)
    else
      flash_warning = t("messages.cant_save", :login_link => "<a style='color:#C9581F;font-weight: bold;' href='/login'><strong>#{t('navigation.with_login')}</strong></a>").html_safe
      @transports_list = Transport.next_dates.has_seats.order("start_time asc").limit(5)
    end

    respond_to do |format|
      format.html { render :new, warning: flash_warning }
      format.json { render json: Transport.transports_data(@transports_list) }
    end
  end
  
  def edit
    @search = Search.find(params[:id])
    authorize! :edit, @search
  end
  
  def update
    @search = Search.find(params[:id])
    authorize! :update, @search

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to my_searches_searches_path, notice: t("messages.search_updated") }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def delete
    @search = Search.find(params[:id])
    authorize! :delete, @search
    
    @search.destroy
    
    respond_to do |format|
      format.html { redirect_to new_search_path, notice: t("messages.search_deleted") }
      format.json { head :ok }
    end
  end
  
  def get_token
    respond_to do |format|
      format.html {render text: "", status: 200}
      format.json {render json: {:csrf_token => form_authenticity_token}, status: 200}
    end
  end

  #########
  protected
  #########
  
  def prepare_list
    if current_user
      @saved_searches = current_user.searches
      @latest_transports = [] #Transport.next_dates.has_seats.order("start_time asc").where("user_id <> #{current_user.id}").where(:user_id => current_user.friends_ids).limit(3)
    else
      @latest_transports = [] #Transport.next_dates.has_seats.order("start_time asc").limit(3)
      
      @saved_searches = []
      @latest_transports = []
    end
  end
  
  def search_results(search)
    @transports = Transport.next_dates.has_seats.order("start_time asc").where("user_id <> #{current_user.id}")
    
    points = []
    factory = ::RGeo::Geographic.simple_mercator_factory()
    
    search.searches_paths.each do |searches_path|
      points << factory.point(searches_path.start_lng, searches_path.start_lat)
    end unless search.searches_paths.blank?
    
    if points.size > 1
      transports_ids = TransportsRoute.next_dates.where("ST_Distance(path, ST_GeomFromText('#{factory.line_string(points).as_text}', 4326) ) < 0.0013").select(:transport_id)
      @transports = @transports.where(:id => transports_ids.collect(&:transport_id))
    end
    
    @transports = @transports.where(:user_id => current_user.friends_ids)
    @transports = @transports.where("start_time >= '#{search.start_time_from}'") unless search.start_time_from.blank?
    @transports = @transports.where("start_time <= '#{search.start_time_to}'") unless search.start_time_to.blank?
    @transports = @transports.where(:cost_type => search.cost_type) unless search.cost_type.blank?
    @transports = @transports.where(:air_cond => search.air_cond) unless search.air_cond.blank?
    @transports = @transports.where(:cassette => search.cassette) unless search.cassette.blank?
    @transports = @transports.where(:smoking => search.cassette) unless search.smoking.blank?
    @transports = @transports.where(:return_back => search.cassette) unless search.return_back.blank?
    
    #todo
    #search within cost
    
    @transports = @transports.page(params[:page]).per(Transport.per_page)
  end
  
  def set_title
    @title = t("searches.searches")
  end
end

app/views/searches/_form.html.erb
<a id="how_to_user_link" href="#"><h4 class="with_icon_big help_bus">كيف أبحث عن توصيلة</h4></a>
<div id="how_to_user" class="list_wrapper high" style="display: none;" >
  <div class="list_container" style="margin-right: 65px;">
    <p><%= t("searches.hint_1")%></p>
    <p><%= t("searches.hint_1_1")%></p>
  </div>
  <div class="clear"></div>
</div>

<% if saved_searches.size > 0 %>
  <a id="saved_transports_link" href="#"><h4 class="with_icon_big car_black_search">البحث المحفوظ سابقا</h4></a>
  <div id="saved_transports" class="list_wrapper high" style="display: none;" >
    <div class="list_container" style="margin-right: 65px;">
      <ul class="notifications_list">
        <% saved_searches.each do |saved_search| %>
          <li>
            <a href="/searches/<%= saved_search.id %>" >
              <%= image_tag("/images/icons/small_car_2.png") %>
              <div>
                <% if !saved_search.start_place.blank? %>
                  <span><%= saved_search.start_place %></span><br/>
                <% elsif !saved_search.start_time_from.blank? %>
                  <span><%= l(saved_search.start_time_from, :format => :short) %></span><br/>
                <% elsif !saved_search.gender.blank? %>
                  <span><%= t("gender.gender_#{saved_search.gender}")%></span><br/>
                <% end %>
    
                <% if !saved_search.searches_paths.blank? %>
                  <span class="small" ><%= saved_search.searches_paths.last.start_place %></label></span>
                <% end %>
              </div>
            </a>
            <br/><%= link_to "حذف هذا البحث", delete_search_path(saved_search), :confirm => "هل أنت متأكد؟"%>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="clear"></div>
  </div>
<% end %>
<%= form_for(search, :method => :post, :url => results_searches_path) do |f| %>
  <%= render :partial=>'/shared/form_errors', :locals=>{:obj => search} %>
  <div id="hidden_fields"></div>
  <a id="adv_search_link" href="#"><h4 class="with_icon_big car_black_search">البحث المتقدم</h4></a>
  <div id="adv_search" style="">
  <div class="form_side">
    <span class="form_item clearfix">
      <%= f.label :start_time_from, :class=>"label_txt" %>
      <span class="required">*</span>
      <%= f.text_field :start_time_from, :class=>"input_txt large date_and_time_picker", :date=> search.start_time_from ? l(search.start_time_from.try(:to_date), :format => :default) : l(Date.today, :format => :default), :hour => search.start_time_from ? search.start_time_from.hour : "0", :minute => search.start_time_from ? search.start_time_from.min : "0" %>
    </span>
    <span class="form_item clearfix">
      <%= f.label :start_time_to, :class=>"label_txt" %>
      <span class="required">*</span>
      <%= f.text_field :start_time_to, :class=>"input_txt large date_and_time_picker", :date=> search.start_time_to ? l(search.start_time_to.try(:to_date), :format => :default) : l(Date.today, :format => :default), :hour => search.start_time_to ? search.start_time_to.hour : "0", :minute => search.start_time_to ? search.start_time_to.min : "0" %>
    </span>
    <span class="form_item clearfix">
      <%= f.label :gender, :class=>"label_txt" %>
      <span class="required">*</span>
      <%= f.select :gender, options_for_select([[t("gender.all_genders"), ""], [t("gender.gender_1"), "1"], [t("gender.gender_2"), "2"]], search.gender), {},:class=>"large" %>
      <div class="help_container">
        <div class="icon" title="تحب تركب مع مين ؟ اختر الجنس الي تحب تروح معاهم في التوصيلة"></div>
      </div>
    </span>
    
    <!-- 
    <span class="form_item clearfix">
      <%= f.label :cost_type , :class=>"label_txt" %>
      <span class="required">*</span>
      <%= f.select :cost_type, options_for_select([[t("gender.all_genders"), ""], [t("cost_type.paid"), 1], [t("cost_type.free"), 2]], search.cost_type), {},:class=>"large" %>
      <div class="help_container">
        <div class="icon" title="تحب تشارك فى البنزين ؟ اختر نوع الدفع الي يناسبك"></div>
      </div>
    </span>
    
    <span class="form_item clearfix">
      <label class="label_txt"><%= t("transports.accessories")%></label>
      <span class="required">*</span>
      <%= f.check_box :air_cond %>
      <span><%= t("transports.air_condition")%></span>
      <%= f.check_box :cassette %>
      <span><%= t("transports.cassette")%></span>
      <%= f.check_box :smoking %>
      <span><%= t("transports.smoking")%></span>
    </span>
    
    -->
    
    <span class="form_item clearfix">
      <%= f.label :return_back, :class=>"label_txt" %>
      <span class="required">*</span>
      <%= f.check_box :return_back %>
      <span><%= t("transports.return_back")%></span>
    </span>
  </div>
  </div>
  
  <div class="map_side" >
    <div class="map">
      <div id="map-canvas" style="width: 575px; height: 400px; "></div>
    </div>
    <div class="clear"></div>
    <div class="advices">
      <p><%= t("transports.hint_2")%></p>
    </div>
    <div class="map_btn">
      <ul class="btn_list">
        <%= render :partial=>'/shared/map_btn', :locals=>{} %>
        <%= render :partial=>'/shared/map_hints', :locals=>{} %>
      </ul>
    </div>
  </div>
  
  <div class="clear"></div>
  <div class="submit clearfix">
    <p>لعرض الكل لا تقم بتحديد اي بيانات</p>
    <%= f.submit :class=>"submit_btn search", :value=> t("searches.searches_search") %>
    
    <div style="float: left; padding: 10px 0 0 0;">
      <%= f.label :save_search, :title => "حفظ البحث عن توصيلة لإعادة إستخدامه لاحقا" %>
      <%= f.check_box :save_search %>
    </div>
  </div>
<% end %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "/stylesheets/jquery-ui-1.8.16.custom.css" %>
<% end %>

<%= content_for :javascripts do %>
  <%= javascript_include_tag "/javascripts/jquery-ui-1.8.16.custom.min.js", "/javascripts/jquery-ui-timepicker-addon.js", "/javascripts/rails.js", "/javascripts/maps.js", "/javascripts/transports.js" %>
  
  <script>
    $(document).ready(function () {
      <% if current_user && current_user.city && current_user.city.lat && current_user.city.lng %>
        cityLat = "<%= current_user.city.lat %>";
        cityLng = "<%= current_user.city.lng %>";
      <% else %>
        cityLat = null;
        cityLng = null;
      <% end %>
      
      if(cityLat && cityLng) {
        myLatlng = new google.maps.LatLng(cityLat, cityLng);
        map.setCenter(myLatlng);
        map.setZoom(13);
      }
      $("#saved_transports_link").click(function(){
        $("#saved_transports").toggle("slow");
        return false;
      })
      
      $("#how_to_user_link").click(function(){
        $("#how_to_user").toggle("slow");
        return false;
      })
      
      $("#adv_search_link").click(function(){
        $("#adv_search").toggle("slow");
        return false;
      })
      
      <% if params[:controller] == "searches" && params[:action] != "results" %>
        $("#adv_search").hide();
      <% end %>
    });
  </script>
  
  <script id="transport_path_templ" type="text/x-jquery-tmpl">
    <div id="hidden_field_${index}">
      <input type="hidden" name="search[searches_paths_attributes][${index}][start_place]" value="${start_place}" >
      <input type="hidden" name="search[searches_paths_attributes][${index}][start_lng]" value="${start_lng}" >
      <input type="hidden" name="search[searches_paths_attributes][${index}][start_lat]" value="${start_lat}" >
    </div>
  </script>
  
  <script id="transport_place_templ" type="text/x-jquery-tmpl">
    <div id="hidden_field_${index}">
      <input type="hidden" name="search[start_place]" value="${start_place}" >
    </div>
  </script>
  
  
<% end %>

app/views/searches/edit.html.erb
<h1>Listing searches</h1>

<%= render :partial => "index" %>


<%= link_to 'New Search', new_search_path %>
<%= link_to 'Back to Search', new_search_path + "?" + params.inspect %>
<%= link_to 'My Searches', my_searches_searches_path  %>











<p id="notice"><%= notice %></p>

<% if @transport.car_profile %>
<p>
  <b>Car Profile:</b>
  <%= @transport.car_profile.cars_make.name + " - " + @transport.car_profile.model_name + " - " + @transport.car_profile.number %>
</p>
<% end %>

<p>
  <b>Start time:</b>
  <%= @transport.start_time %>
</p>

<p>
  <b>Allowed persons:</b>
  <%= @transport.allowed_persons %>
</p>

<p>
  <b>Cost type:</b>
  <%= @transport.cost_type %>
</p>

<p>
  <b>Cost:</b>
  <%= @transport.cost %>
</p>

<p>
  <b>Air cond:</b>
  <%= @transport.air_cond %>
</p>

<p>
  <b>Cassette:</b>
  <%= @transport.cassette %>
</p>

<p>
  <b>Smoking:</b>
  <%= @transport.smoking %>
</p>

<p>
  <b>Return back:</b>
  <%= @transport.return_back %>
</p>

<div style="border: 1px solid blue">
  <h2>Paths</h2>
  <% @transport.points_list.each do |point| %>
  <div style="border: 1px solid black">
    <p>
      <b>Start Place:</b>
      <%= point.x %> - <%= point.y %> 
    </p>
  </div>
  <% end %>
</div>



<div style="border: 1px solid blue">
  <h2>Requests</h2>
  <% @transport.transports_requests.each do |transports_request| %>
  <div style="border: 1px solid black">
    <p>
      <b>Status :</b>
      <%= transports_request.status %>
    </p>
    <p>
      <b>User :</b>
      <%= transports_request.user.name %>
    </p>
    <p>
      <b>Message :</b>
      <%= transports_request.requester_message %>
    </p>
    <p>
      <b>Meet Place :</b>
      <%= transports_request.requester_meet_place %>
    </p>
    <p>
      <td><%= link_to 'Response', transports_response_transport_transports_request_path(transports_request.transport, transports_request) %></td>
      
      <td><%= link_to 'Update response', edit_transport_transports_request_path(transports_request.transport, transports_request) %></td>
      
      
      <td><%= link_to 'Delete', delete_transport_transports_request_path(transports_request.transport, transports_request) %></td>

      <% transports_request_rate = transports_request.rates.where(:user_id => current_user.id).first %>
      <% if transports_request_rate %>
        <td><%= link_to 'Edit Rate', edit_transport_transports_request_rate_path(transports_request.transport, transports_request, transports_request_rate.id) %></td>
      <% else %>
        <td><%= link_to 'Rate', new_transport_transports_request_rate_path(transports_request.transport, transports_request) %></td>
      <% end %>
    </p>
  </div>
  <% end %>
</div>


<%= link_to 'Edit', edit_transport_path(@transport) %> |
<%= link_to 'Back', transports_path %>

app/views/searches/my_searches.html.erb
<h1>My Searches</h1>

<table>
  <tr>
    <th>Start time</th>
    <th>Allowed persons</th>
    <th>Cost type</th>
    <th>Cost</th>
    <th>Air cond</th>
    <th>Cassette</th>
    <th>Smoking</th>
    <th>Return back</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @searches.each do |transport| %>
  <tr>
    <td><%= transport.search_name %></td>
    <td><%= transport.cost_type %></td>
    <td><%= transport.air_cond %></td>
    <td><%= transport.cassette %></td>
    <td><%= transport.smoking %></td>
    <td><%= transport.return_back %></td>
    <td><%= link_to 'Show', transport %></td>
    <td><%= link_to 'Edit', edit_search_path(transport) %></td>
    <td><%= link_to 'Destroy', delete_search_path(transport) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<div class="main_page_content">
  <h2 class="page_title"><%= t("searches.searches") %></h2>
  <div class="content_container">
    <% if @transports_list && @transports_list.size > 0 %>
    <div class="sub_page_content" style="margin-bottom: 35px;">
      <h3 class="title">أجدد التوصيلات</h3>
      <div class="sub_page_container">
        
        <div class="list_wrapper">
          <div class="list_container">
            <% @transports_list.each do |transport| %>
              <%= render :partial => "/transports/transport", :locals => {:transport => transport, :adv_view => true}%>
            <% end %>
          </div>
        </div>
        
      </div>
    </div>
    <% end %>
    
    <div class="sub_page_content">
      <h3 class="title">البحث عن توصيلة</h3>
      <div class="sub_page_container">
        <%= render :partial => '/searches/form', :locals=>{:search => @search, :saved_searches => @saved_searches} %>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar do %>
  <%= render :partial => "/shared/sidebar/latest_transports", :locals=>{:transports => @latest_transports} %>
  <%= render "/shared/sidebar/invite_friends" %>
  <%= render "/shared/sidebar/like_box" %>
<% end %>

<% content_for :javascripts do %>
  <%= javascript_include_tag "/javascripts/stars.js" %>
<% end %>

app/views/searches/results.html.erb
<div class="main_page_content">
  <h2 class="page_title"><%= t("transports.transports")%></h2>
  <%= render :partial => "/transports/index", :locals => {:transports => @transports, :prev_transports => [], :hint => t("searches.hint_2")}%>
</div>

<% content_for :sidebar do %>
  <%= render "/shared/sidebar/invite_friends" %>
  <%= render "/shared/sidebar/like_box" %>
  <%= render "/shared/sidebar/credits" %>
<% end %>

app/views/searches/show.html.erb
<div class="main_page_content">
  <h2 class="page_title"><%= t("transports.transports")%></h2>
  <%= render :partial => "/transports/index", :locals => {:transports => @transports, :prev_transports => [], :hint => t("searches.hint_2")}%>
</div>

<% content_for :sidebar do %>
  <%= render "/shared/sidebar/credits" %>
<% end %>